# See http://doc.gitlab.com/ce/ci/yaml/ for documentation.
Build and Check (x86-64):
  script:
  - ./.bootstrap &&
    ./configure --disable-documentation && make -j4 &&
    make check -j4
  tags:
  - x86-64
  except:
  - tags
Build and Check (x86):
  script:
  - ./.bootstrap &&
    ./configure --disable-documentation && make -j4 &&
    make check -j4
  tags:
  - x86
  except:
  - tags
Build and Check with mini-gmp:
  script:
  - ./.bootstrap &&
    ./configure --disable-documentation --enable-mini-gmp && make -j4 &&
    make check -j4
  tags:
  except:
  - tags
Build and Check with ubsan:
  script:
  - ./.bootstrap && 
    CXXFLAGS="-fsanitize=undefined -fno-sanitize-recover -g -O2" CFLAGS="-fsanitize=undefined -fno-sanitize-recover -g -O2" ./configure 
    --disable-documentation && make -j4 && make check -j4
  tags:
  - ubsan
  except:
  - tags
Build and Check with asan:
  script:
  - ./.bootstrap && 
  - CXXFLAGS="-fsanitize=address -g -O2" CFLAGS="-fsanitize=address -g -O2" ./configure --disable-documentation &&
    make -j4 && make check -j4
  except:
  - tags
